### ISSUE TITLE
Would be handy to note how to add labels to points

### ISSUE THREAD

**Issue by brantfaircloth** [omys-omics/triangulaR#1]
Hi Ben,

This is a super cool and handy package - thanks!

I've been playing with it using a few data sets, and one thing that I think would be helpful would be to allow passing an option to `triangle.plot` that easily outputs labels for each individual.  I know this gets messy, but it's also really handy to know which individuals fall within parts of the plot can also be very useful.

That said, because it's a ggplot object, just noting that you can add something like `+ geom_label_repel(aes(label=id), size=2)` to `triangle.plot` would be just as useful.  I had to look in the code to figure out how to do this (which wasn't bad), but making this a little more easy would be awesome.

Thanks again,
b

**Comment by omys-omics** [comment]
Hi Brant,

Thanks for the suggestion! I've added an option to the ```triangle.plot``` and ```missing.plot``` functions to allow individual labeling. Setting ```ind.labels = T``` will label individuals on the plot, and increasing ```max.overlaps``` will increase the amount of individuals that are labeled, even if they are really close together.

Hope this helps!

**Comment by brantfaircloth** [comment]
Awesome - thanks - this is great!
